# Site settings
title: simonpalmqvist
email: simon.palmqvist@gmail.com
description: >
  Developer, designer & beer brewer.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "https://simonpalmqvist.github.io" # the base hostname & protocol for your site
url: "http://localhost:4000"
twitter_username: simonpalmqvist
github_username:  simonpalmqvist
logo: "/assets/images/logo.png"

# Build settings
markdown: kramdown
paginate: 2
paginate_path: "/blog/page:num/"
collections:
  beers:
      output: true
      permalink: "/beer/:name/"