# Site settings
title: simonpalmqvist
email: your-email@domain.com
description: >
  I'm a developer, designer & beer brewer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: simonpalmqvist
github_username:  simonpalmqvist

# Build settings
markdown: kramdown
paginate: 10