# Site settings
title: simonpalmqvist
creator: Simon Palmqvist
creator_location: Berlin, Germany
creator_origin: Örebro, Sweden
creator_img: "/assets/images/simon.jpg"
email: simon.palmqvist@gmail.com
description: >
  Web developer & designer who loves to create stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://simonpalmqvist.github.io" # the base hostname & protocol for your site
twitter_username: simonpalmqvist
github_username:  simonpalmqvist
logo: "/assets/images/logo.png"

# Build settings
markdown: kramdown
paginate: 3
paginate_path: "/blog/page:num/"
collections:
  beers:
      output: true
      permalink: "/beer/:name/"