# Site settings
title: simonpalmqvist
email: simon.palmqvist@gmail.com
description: >
  Developer, designer & beer brewer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: simonpalmqvist
github_username:  simonpalmqvist

# Build settings
markdown: kramdown
paginate: 2
paginate_path: "/blog/page:num/"